version: '3'

services:
  react_native_expo:
    image: 'nortmas/react-native-expo'
    command: react-native-expo-app
    ports:
      - 3000:3000
    volumes:
      - ./react-native-expo-app:/react-native-expo-app
